### PR TITLE
Add Android Guides example

### PR DESCRIPTION
**Pull request by MSF-Jarvis**
Shout out to codepath and the awesome plugin authors for making my life easier :+1:

### CODE REVIEW

**Comment by MSF-Jarvis** [comment]
@mholt? Why u no merge? :(

**Comment by mholt** [comment]
Patience. :) It was the weekend.

**Comment by mholt** [comment]
This is nice, and thanks for submitting the PR, but I wonder how many people actually have this use case? I'm not sure it's generally applicable enough to the wider Caddy audiences to include in this repository.

**Comment by MSF-Jarvis** [comment]
Well I find them pretty useful and the dozen or so friends I suggested this
found it extremely helpful too but it's your call at the end, I already
have this up on my blog ;)

**Pull request closed without merging**
