### PR TITLE
disable timeout on git clone for gitea service

### PR DESCRIPTION
**Pull request by appleboy**
error: RPC failed; curl 18 transfer closed with outstanding read data remaining

### CODE REVIEW

**Comment by mholt** [comment]
The good news is that the next version of Caddy won't have default timeouts enabled anymore, so this won't be necessary. :)

**Comment by appleboy** [comment]
@mholt I can remove timeout flag on `Drone` example on next version of Caddy?

**Comment by mholt** [comment]
@appleboy Yep!

**Comment by appleboy** [comment]
@mholt Good news... Thanks.

**Pull request closed without merging**
