### PR TITLE
Django and phabricator examples

### PR DESCRIPTION
**Pull request by jordic**

### CODE REVIEW

**Comment by mholt** [comment]
Thanks!

Does the phabricator tutorial need any more explanation?

**Comment by jordic** [comment]
I think not. Perhaps we can tell there that they can follow phabricator own tutorial, and replace nginx part for this caddyfile.

**Comment by mholt** [comment]
That's good!

Last thing: can you fix the alignment of the indents? Preferably tab indent. Just one tab per indent level. That'll make it look clean, easier to read. Then I can merge this!

**Comment by jordic** [comment]
Done!

**Comment by mholt** [comment]
Thanks!

**Pull request merged**
